PSTRESS-77 Add support for keyring component in pstress
Percona-QA/pstress pull request #27
Opened 2021-05-26 09:20 UTC by mohitj1988

Problem: With the introduction of keyring components in MySQL 8.0.24, it is now
possible to use either plugin or component infrastructure for keyring encryption

Solution: Implemented an option to enable/disable keyring component.
For PS-5.7 runs, we will continue to use keyring plugin as components are unsupported
For PS-8.0 runs, by default components will be used for keyring encryption
Similar changes has been added for PXC-5.7 and PXC-8.0

2021-05-26 10:55 UTC, rahulmalik87 reviewed
are you preserving the key file anywhere to reproduce the bug? 
also to support multiple pstress run. It is better to use local cnf file.

also please ensure that it works with default encryption enabled.

2021-06-01 09:54 UTC, mohitj1988 commented
1. The keyring file is created inside plugin directory which is copied in the workdir. 
2. Both global and local manifest files pair is used along with global and local config file. The local config file is created inside the datadirectory.
3. For 5.7, keyring component feature is disabled since it is unsupported.
4. For 8.0, both keyring plugin and keyring component are supported in pstress. keyring component is enabled by default. However, if a user wish to use keyring plugin, then keyring component can be disabled. 
Using keyring component automatically disabled keyring plugin and vice versa.

2021-06-01 16:18 UTC, altmannmarcelo approved these changes
from a keyring component point of view, the configuration looks correct.

2021-06-01 23:46 UTC, rahulmalik87 requested changes
could you paste result of pstress run with default encryption enabled in configrations.

2021-06-02 11:30 UTC, mohitj1988 commented
> could you paste result of pstress run with default encryption enabled in configrations like redo/undo system etc

./pstress-run.sh pstress-run.conf
[09:54:31] [0] MODE: Multi threaded pstress testing
[09:54:31] [0] Workdir: /home/mohit.joshi/pstress_runs/ps/8.0/672753 | Rundir: /tmp/672753 | Basedir: /home/mohit.joshi/upstream-8.0/bld_8.0.25/install/ 
[09:54:31] [0] mysqld Start Timeout: 60 | Client Threads: 10 | Queries/Thread: 100000 | Trials: 5 | Save coredump/valgrind issue trials only: FALSE
[09:54:31] [0] Valgrind run: FALSE | pstress timeout: 60
[09:54:31] [0] pstress Binary: /home/mohit.joshi/pstress_77/pstress/../src/pstress-ms
[09:54:31] [0] MYSAFE: --no-defaults --max_allowed_packet=33554432 --default_table_encryption=ON --innodb_redo_log_encrypt=ON --innodb_undo_log_encrypt=ON --binlog_encryption=ON --log-output=none --sql_mode=ONLY_FULL_GROUP_BY
[09:54:31] [0] Making a copy of the pstress binary used (/home/mohit.joshi/pstress_77/pstress/../src/pstress-ms) to /home/mohit.joshi/pstress_runs/ps/8.0/672753/ (handy for later re-runs/reference etc.)
[09:54:31] [0] Creating global manifest file mysqld.my
[09:54:31] [0] Creating global configuration file component_keyring_file.cnf
[09:54:31] [0] Making a copy of the mysqld binary into /home/mohit.joshi/pstress_runs/ps/8.0/672753/mysqld (handy for coredump analysis and manually starting server)...
[09:54:32] [0] Making a copy of the library files required for starting server from incident directory
[09:54:32] [0] Making a copy of the conf file pstress-run.conf(useful later during repeating the crashes)...
[09:54:32] [0] Making a copy of the seed file...
[09:54:32] [0] Generating datadir template (using mysql_install_db or mysqld --init)...
[09:54:47] [0] Starting pstress testing iterations...
[09:54:47] [0] ====== TRIAL #1 ======
[09:54:47] [0] Ensuring there are no relevant servers running...
[09:54:47] [0] Clearing rundir...
[09:54:47] [0] Generating new trial workdir /tmp/672753/1...
[09:54:47] [0] Copying datadir from template...
[09:54:48] [0] Creating local manifest file mysqld.my
[09:54:48] [0] Creating local configuration file component_keyring_file.cnf
[09:54:48] [0] Starting mysqld. Error log is stored at /tmp/672753/1/log/master.err
[09:54:48] [0] Waiting for mysqld (pid: 284182) to fully start (note this is slow for Valgrind runs, and can easily take 35-90 seconds even on an high end server)...
[09:55:49] [0] Server started ok. Client: /home/mohit.joshi/upstream-8.0/bld_8.0.25/install//bin/mysql -uroot -S/tmp/672753/1/socket.sock
[09:55:49] [0] Creating metadata randomly using random seed 672753 ...
[09:55:49] [0] /home/mohit.joshi/pstress_77/pstress/../src/pstress-ms --database=test --threads=10 --queries-per-thread=100000 --logdir=/tmp/672753/1 --user=root --socket=/tmp/672753/1/socket.sock --seed 672753 --step 1 --metadata-path /home/mohit.joshi/pstress_runs/ps/8.0/672753/ --seconds 60 --tables 5 --records 100 --log-all-queries --log-failed-queries --mso=innodb_redo_log_encrypt=ON=OFF --mso=innodb_undo_log_encrypt=ON=OFF --mso=default_table_encryption=ON=OFF
[09:55:49] [0] pstress running (Max duration: 60s)...
[09:56:51] [0] 60s timeout reached. Terminating this trial...
[09:56:51] [0] TIMEOUT_INCREMENT option was disabled and set to 0
[09:56:51] [0] Cleaning up & saving results if needed...
[09:56:53] [0] Killing the server with Signal 9
[09:56:54] [0] pstress run details: 124/2218 queries failed, (94.41% were successful)
[09:56:54] [0] Copying rundir from /tmp/672753/1 to /home/mohit.joshi/pstress_runs/ps/8.0/672753/1
[09:56:54] [1] ====== TRIAL #2 ======
[09:56:54] [1] Ensuring there are no relevant servers running...
[09:56:54] [1] Clearing rundir...
[09:56:54] [1] Generating new trial workdir /tmp/672753/2...
[09:56:54] [1] Copying datadir from Trial /home/mohit.joshi/pstress_runs/ps/8.0/672753/1 into /home/mohit.joshi/pstress_runs/ps/8.0/672753/2...
[09:56:54] [1] Starting mysqld. Error log is stored at /tmp/672753/2/log/master.err
[09:56:54] [1] Waiting for mysqld (pid: 285068) to fully start (note this is slow for Valgrind runs, and can easily take 35-90 seconds even on an high end server)...
[09:57:56] [1] Server started ok. Client: /home/mohit.joshi/upstream-8.0/bld_8.0.25/install//bin/mysql -uroot -S/tmp/672753/2/socket.sock
[09:57:56] [1] Loading metadata from /home/mohit.joshi/pstress_runs/ps/8.0/672753/step_1.dll ...
[09:57:56] [1] /home/mohit.joshi/pstress_77/pstress/../src/pstress-ms --database=test --threads=10 --queries-per-thread=100000 --logdir=/tmp/672753/2 --user=root --socket=/tmp/672753/2/socket.sock --seed 672753 --step 2 --metadata-path /home/mohit.joshi/pstress_runs/ps/8.0/672753/ --seconds 60 --tables 5 --records 100 --log-all-queries --log-failed-queries --mso=innodb_redo_log_encrypt=ON=OFF --mso=innodb_undo_log_encrypt=ON=OFF --mso=default_table_encryption=ON=OFF
[09:57:56] [1] pstress running (Max duration: 60s)...
[09:58:57] [1] 60s timeout reached. Terminating this trial...
[09:58:57] [1] TIMEOUT_INCREMENT option was disabled and set to 0
[09:58:57] [1] Cleaning up & saving results if needed...
[09:58:59] [1] Killing the server with Signal 9
[09:59:00] [1] pstress run details: 170/4726 queries failed, (96.40% were successful)
[09:59:00] [1] Copying rundir from /tmp/672753/2 to /home/mohit.joshi/pstress_runs/ps/8.0/672753/2
[09:59:00] [2] ====== TRIAL #3 ======
[09:59:00] [2] Ensuring there are no relevant servers running...
[09:59:00] [2] Clearing rundir...
[09:59:00] [2] Generating new trial workdir /tmp/672753/3...
[09:59:00] [2] Copying datadir from Trial /home/mohit.joshi/pstress_runs/ps/8.0/672753/2 into /home/mohit.joshi/pstress_runs/ps/8.0/672753/3...
[09:59:01] [2] Starting mysqld. Error log is stored at /tmp/672753/3/log/master.err
[09:59:01] [2] Waiting for mysqld (pid: 285947) to fully start (note this is slow for Valgrind runs, and can easily take 35-90 seconds even on an high end server)...
[10:00:03] [2] Server started ok. Client: /home/mohit.joshi/upstream-8.0/bld_8.0.25/install//bin/mysql -uroot -S/tmp/672753/3/socket.sock
[10:00:03] [2] Loading metadata from /home/mohit.joshi/pstress_runs/ps/8.0/672753/step_2.dll ...
[10:00:03] [2] /home/mohit.joshi/pstress_77/pstress/../src/pstress-ms --database=test --threads=10 --queries-per-thread=100000 --logdir=/tmp/672753/3 --user=root --socket=/tmp/672753/3/socket.sock --seed 672753 --step 3 --metadata-path /home/mohit.joshi/pstress_runs/ps/8.0/672753/ --seconds 60 --tables 5 --records 100 --log-all-queries --log-failed-queries --mso=innodb_redo_log_encrypt=ON=OFF --mso=innodb_undo_log_encrypt=ON=OFF --mso=default_table_encryption=ON=OFF
[10:00:03] [2] pstress running (Max duration: 60s)...
[10:01:04] [2] 60s timeout reached. Terminating this trial...
[10:01:04] [2] TIMEOUT_INCREMENT option was disabled and set to 0
[10:01:04] [2] Cleaning up & saving results if needed...
[10:01:06] [2] Killing the server with Signal 9
[10:01:07] [2] pstress run details: 138/4078 queries failed, (96.62% were successful)
[10:01:07] [2] Copying rundir from /tmp/672753/3 to /home/mohit.joshi/pstress_runs/ps/8.0/672753/3
[10:01:07] [3] ====== TRIAL #4 ======
[10:01:07] [3] Ensuring there are no relevant servers running...
[10:01:07] [3] Clearing rundir...
[10:01:07] [3] Generating new trial workdir /tmp/672753/4...
[10:01:07] [3] Copying datadir from Trial /home/mohit.joshi/pstress_runs/ps/8.0/672753/3 into /home/mohit.joshi/pstress_runs/ps/8.0/672753/4...
[10:01:07] [3] Starting mysqld. Error log is stored at /tmp/672753/4/log/master.err
[10:01:07] [3] Waiting for mysqld (pid: 286925) to fully start (note this is slow for Valgrind runs, and can easily take 35-90 seconds even on an high end server)...
[10:02:09] [3] Server started ok. Client: /home/mohit.joshi/upstream-8.0/bld_8.0.25/install//bin/mysql -uroot -S/tmp/672753/4/socket.sock
[10:02:09] [3] Loading metadata from /home/mohit.joshi/pstress_runs/ps/8.0/672753/step_3.dll ...
[10:02:09] [3] /home/mohit.joshi/pstress_77/pstress/../src/pstress-ms --dat [...]

2021-06-02 14:54 UTC, rahulmalik87 approved these changes
LGTM

2021-06-03 03:28 UTC, merged