PSTRESS-137 Add support for ALTER INSTANCE RELOAD KEYRING DDL in pstress
Percona-QA/pstress pull request #76
Opened 2022-10-26 06:50 UTC by mohitj1988

2022-10-26 09:03 UTC, rahulmalik87 requested changes

2022-11-02 12:40 UTC, mohitj1988 commented on src/help.cpp
> +  opt->setInt(0);
We don't want to enable this DDL by default. The purpose of this DDL comes into affect when a user changes the global or local manifest file and wants to reload the new configuration to be read from manifest files. Enabling this DDL will not achieve any purpose unless we are testing keyring component related feature.

2022-11-03 02:14 UTC, rahulmalik87 commented on src/help.cpp
> +  opt->setInt(0);
Even if the manifest file doesn't change, Reloading will execute some code path which can tested with another concurrent load.
Like how it behaves with ALTER INSTANCE ROTATE KEY. 
 For this reason, I would enable it by default with a very low probability.

2023-01-30 06:39 UTC, rahulmalik87 commented on src/help.cpp
> +  opt->setInt(0);
@mohitj1988 Please address this whenever you get time.

2023-02-13 03:06 UTC, mohitj1988 commented on src/help.cpp
> +  opt->setInt(0);
Fixed. Kindly check

2023-02-13 05:47 UTC, rahulmalik87 reviewed
Pstress disables encryption-related options if --no-encryption is passed. can also disable "Alter instance reload kyering"  if --no-encryption is given.

2023-02-13 06:21 UTC, rahulmalik87 approved these changes
LGTM

2023-02-13 06:22 UTC, merged