PSTRESS-138: Crashes caused by dangling pointers
Percona-QA/pstress pull request #77
Opened 2022-10-28 06:57 UTC by kamil-holubicki

access, out of bound array access

https://jira.percona.com/browse/PSTRESS-138

Fixed problems:
1. usage of the pointer pointing to deallocated MYSQL_RES (get_result() and execute_sql() functions)
2. out of bound array indexing in case of the result having fewer fields than expected
3. Uncaught exceptions thrown by thread routine
4. Wrong parsing of the config file in case of PXC_CLUSTER_RUN=1

2022-11-07 05:42 UTC, rahulmalik87 requested changes

2022-11-07 05:42 UTC, rahulmalik87 commented on src/random_test.cpp
> +  result = get_result("select @@innodb_sys_tablespace_encrypt", thd);
for MySQL this variables don't exists. and in that case, It throws and all other threads fall in infinite loop.

2022-11-07 08:07 UTC, VarunNagaraju approved these changes

2022-11-21 08:53 UTC, kamil-holubicki commented
These ideas were incorporated by @rahulmalik87 in other PR

2022-11-21 08:53 UTC, closed without merging